/**
 * Created by Administrator on 2017/12/28.
 */
// 函数的名字
export const ACTIONS_DEL_SHOPPINGCAR = 'ACTIONS_DEL_SHOPPINGCAR'     //actions 方法中删除的方法
export const ACTIONS_ADD_SHOPPINGCAR = 'ACTIONS_ADD_SHOPPINGCAR'
export const MUTATIONS_DEL_SHOPPINGCAR = 'MUTATIONS_DEL_SHOPPINGCAR'
export const MUTATIONS_ADD_SHOPPINGCAR = 'MUTATIONS_ADD_SHOPPINGCAR'
